### ISSUE TITLE
d3_breen_01 when player reach this map via transition or start it from map dialog, player spawned outside pod

### ISSUE THREAD

**Issue by Sp-Lily** [ZehMatt/Lambda#101]
Details of the occuring bug:
- If reaching the map via transition, you're spawned in a dummy room
- If starting the map from map dialog, you're spawned outside 2 combine soldiers & Dr. Mossman room

**Comment by Balimbanana** [comment]
Need `trigger_multiple`'s with the output: `"OnTrigger" "pod,EnterVehicleImmediate,,0,-1"` placed in the transition room and the main spawnpoint. Then remove the triggers after the pod is destroyed.
Can use precached models `"*98"` or `"*100"` for the trigger volumes.

There is a problem, the first room has flashing props, not entirely sure why, but it is a problem in other multiplayer Source games running `d3_breen_01` as well.

**Comment by Sp-Lily** [comment]
Is Synergy have that flashing props?

**Comment by Balimbanana** [comment]
Yes, but specifically when connected to a dedicated server. Listen server is unaffected in Synergy.
In GMod, both listen and dedicated server is affected.

**Comment by ZehMatt** [comment]
I should maybe mention that the last few maps in Half-Life 2 have been poorly made, you can literally tell that they just wanted to get it done. Like has anyone ever noticed that there are no visible path tracks for your pod when entering the room with Mossman?

**Comment by Sp-Lily** [comment]
Yes I saw that when I switch my perspective into 3rd person

**Comment by Sp-Lily** [comment]
Is this bug fixed in 0.9.2?

**Comment by ZehMatt** [comment]
No, also that players spawn outside of the pods is more or less wanted since its hard to make players believe they are on a path track while there is none. I decided on this map that players better start off outside of the door and hear that something is going on inside.

**Comment by Sp-Lily** [comment]
Then how to progress normally?

**Comment by ZehMatt** [comment]
I have to yet look at the actual transitioning bug, no progress there yet, sorry.

**Comment by Sp-Lily** [comment]
No probs, I'll be wait for the upcoming news for this transition bug

**Comment by ZehMatt** [comment]
Should be fixed.

**Comment by Balimbanana** [comment]
The flashing bug was fixed in Synergy by a late parenting. In EDT format:

		create {classname "func_tracktrain" origin "-2436 -1406 159"
			values
			{
				targetname "syn_podtrain"
				target "syn_podpath1"
				angles "90 -90 0"
				speed "70"
				orientationtype "1"
			}
		}
		edit {targetname "pod" values {DisableShadows "1" parentname "syn_podtrain"} }
		create {classname "path_track" origin "-2430 -1386 110"
			values
			{
				targetname "syn_podpath1"
				angles "0 0 0"
				target "syn_podpath2"
			}
		}
		create {classname "path_track" origin "-2430 -1386 667"
			values
			{
				targetname "syn_podpath2"
				angles "0 0 0"
				target "syn_podpath3"
				OnPass "pod,SetParent,Breen_arm_player,1,-1"
				OnPass "pod,SetParentAttachment,eli_pod_inner_attachment,1.1,-1"
			}
		}
