### ISSUE TITLE
"Physcannon Mega" weird grabbing

### ISSUE THREAD

**Issue by Sp-Lily** [ZehMatt/Lambda#102]
To produce this weird grab, play in citadel level and try to grab Combine's console or monitor that attached to the wall. Those physics actually require small amount of time until fully unattached, but Mega Physcannon can grab it even it's not unattached yet

**Comment by Balimbanana** [comment]
I am pretty sure this has to do with the prop prediction, not too sure exactly what could be done. Maybe there is a way to prevent prediction on specific entities grabbed by the mega physcannon?

You can see it if you use `sv_client_predict -1` Then on client: `cl_predict 0`

**Comment by Sp-Lily** [comment]
I'll try that. If that fix the Mega Physcannon, then this mod should set those console command automatically

**Comment by Balimbanana** [comment]
The problem is that movement is laggy without prediction, which is why it would have to be coded (if possible) to only remove prediction from the mega physcannon. It isn't so bad with less than 50 latency, but even then it is a little sluggish.

**Comment by ZehMatt** [comment]
This is something I can not fix currently, the detach logic happens server side while the client has already initialized the physics object for prediction and attached it. There is currently no event I could hook up to delay the attachment on the client.

**Comment by Sp-Lily** [comment]
I see both console commands works perfect to prevent the weird grab on specific props. The console wrote there are 5 predicted props entity (Tested in d3_citadel_03)

**Comment by ZehMatt** [comment]
I've implemented something that will compensate for this situation, I think you guys will be happy with the outcome, its not perfect but will make up for 99% of the cases.
