### ISSUE TITLE
Env_Zoom and better point_viewcontrol entities for cutscenes needs to be added.

### ISSUE THREAD

**Issue by Balimbanana** [ZehMatt/Lambda#103]
From a sample easy way to re-add env_zoom functionality in multiplayer I wrote some time last year:
entities/entities/env_zoom/init.lua

	AddCSLuaFile( "cl_init.lua" ) 
	AddCSLuaFile( "shared.lua" ) 

	include('shared.lua')
 
	function ENT:KeyValue(key, value)
		if (key:lower() == "fov") then
			self.fov = value
		elseif (key:lower() == "rate") then
			self.rate = value
		elseif (key:lower() == "allplayers") then
			self.allply = value
		end
	end
	 
	function ENT:Initialize()
		self.allply = 1
	end
	  
	function ENT:Use( activator, caller )
	end
	
	function ENT:Think()
	end
	
	function ENT:AcceptInput(inputName, activator, called, data)
		
		if (inputName == "Zoom") then
		
			--print("Setting ply fov to: "..self.fov.." at a rate of: "..self.rate)
			if (self.allply == 0) then
				activator:SetFOV(self.fov, self.rate)
			elseif ((self.allply == 1) or (self.allply == nil) or (self.allply == '')) then
				for k,ply in pairs(player.GetAll()) do
					ply:SetFOV(self.fov, self.rate)
				end
			end
			
		elseif (inputName == "UnZoom") then
		
			if (self.allply == 0) then
				activator:SetFOV(self.fov, self.rate)
			elseif ((self.allply == 1) or (self.allply == nil) or (self.allply == '')) then
				for k,ply in pairs(player.GetAll()) do
					ply:SetFOV(90, self.rate)
				end
			end
		end
	end

shared.lua:

	ENT.Type = "point"
	ENT.Base = "base_point"

cl_init.lua:

	include('shared.lua')

The point_viewcontrol remake is a bit more problematic, but still functional as this:
entities/entities/point_viewcontrol/init.lua

	AddCSLuaFile( "cl_init.lua" ) 
	AddCSLuaFile( "shared.lua" ) 

	include('shared.lua')
 
	function ENT:KeyValue(key, value)
		if (key:lower() == "angles") then
			self.ang = value
		elseif (key:lower() == "wait") then
			self.holdtime = value
		elseif (key:lower() == "allplayers") then
			self.allply = value
		end
	end
 
	function ENT:Initialize()
		self.allply = 1
		entsusing = {}
	end
  
	function ENT:Use( activator, caller )
	end
  
	function ENT:Think()
	end

	function ENT:AcceptInput(inputName, activator, called, data)
	
		if (inputName:lower() == "enable") then
	
			if ((self.viewent == nil) or (self.viewent == '') or (!IsValid( self.viewent ))) then
				local ent = ents.Create( "prop_physics" )
				ent:SetModel( "models/hunter/misc/sphere025x025.mdl" )
				ent:SetPos( self:GetPos() )
				--Tried EyeAngles, EyePos, GetAngles
				ent:SetAngles( Angle(self.ang) )
				ent:SetKeyValue("parentname", self:GetName())
				ent:Spawn()
				ent:SetMoveType(MOVETYPE_FLY)
				ent:SetRenderMode(RENDERMODE_NONE)
				self.viewent = ent
			end
			--[[
			if (!self:HasSpawnFlags(8)) then
				print("Removing view ent after: "..self.holdtime)
				timer.Simple(self.holdtime, function() ent:Remove() end )
			else --For now, just remove after 60 seconds maybe?
				timer.Simple(60, function() ent:Remove() end )
			end
			--View self.viewent removed on disable
			]]

			if (self.allply == 0) then
				local curfov = activator:GetFOV()
				activator:Spectate( OBS_MODE_IN_EYE )
				activator:SpectateEntity( self.viewent )
				activator:SetFOV(curfov, 0.0)
				if (!table.HasValue( entsusing, activator )) then
					entsusing.insert(activator)
				end
			elseif ((self.allply == 1) or (self.allply == nil) or (self.allply == '')) then
				for _, ply in pairs( player.GetHumans() ) do
					local curfov = ply:GetFOV()
					ply:Spectate( OBS_MODE_IN_EYE )
					ply:SpectateEntity( self.viewent )
					ply:SetFOV(curfov, 0.0)
				end
			end
		
		elseif (inputName:lower() == "disable") then
		
			if (self.allply == 0) then
				activator:UnSpectate()
				activator:Spawn()
				for k, v in ipairs(entsusing) do
					if ((v == activator) or (!v:IsConnected())) then
						table.RemoveByValue( entsusing, v )
					end
				end
				if (#entsusing < 1) then
					self.viewent:Fire( "kill" )
					self.viewent = nil
				end
			elseif ((self.allply == 1) or (self.allply == nil) or (self.allply == '')) then
				for k, ply in pairs( player.GetHumans() ) do
					ply:UnSpectate()
					ply:Spawn()
				end
				self.viewent:Fire( "kill" )
			end
			
		end
	end

Remember that I wrote this about a year ago, and there may be better ways of doing these things, but this has been an issue that has bugged me for Lambda and I want this fixed.

Edited for allplayers key, default to on, but can be turned off for both env_zoom and point_viewcontrol.

**Comment by ZehMatt** [comment]
Your workaround comes with other problems, you can't assume that whenever "Enable" is fired that every player should be affected. There are some binoculars in the coast and prison maps, so when one player would use them everyone would be affected. But I'll have a look into this, thanks for pointing this out.

**Comment by Balimbanana** [comment]
Could try adding a spawnflag for all players vs one player maybe, or a keyvalue. Not sure if it should be one that is on by default, then using the map scripts, set for one player or not.

**Comment by ZehMatt** [comment]
I've been thinking that if the activator is the player it should only affect the player otherwise its meant to be global? I need to run some tests on this first, it will also take a while to properly backport it as some lua entity.

**Comment by Balimbanana** [comment]
Might have to do that as well for the point_viewcontrol, but almost all of them should be active for all players, there are some (like the one on the coast) that should also be just activator.

**Comment by Balimbanana** [comment]
I edited the original post to include the `allplayers` key. It is default to on for both `env_zoom` and `point_viewcontrol`, and I tested it a bit here and there, but you can test it your self to make sure.

The `point_viewcontrol` view entity now removes on disable, unless it is set for activator only, then it uses the table `entsusing`.

**Comment by ZehMatt** [comment]
It would be nice if you could open a PR and base this on lambda_entity, there are functions for keyvalues and inputs already.

**Comment by Balimbanana** [comment]
There are just a couple things I want to ask/point out.
Line 41: Default wait is usually 8 or 10 for SourceMods.
Line 42: Default speed is usually 0 or 100 for SourceMods.
Line 44: `Target` is what entity this viewcontrol is supposed to be looking at, not its `targetname`.
It does need a `targetname` `KeyValue` though.
Line 235: Will the player be unfrozen on disable? Should maybe add it in case in `RestorePlayer`
Line 288: Should also include the `AllPlayers` kv as an `or` statement, as the spawnflag may not always be set, or should it?
Line 332: Could either use the `activator` position, or the first connected client.

**Comment by ZehMatt** [comment]
I'm aware, currently I'm trying to see why it would never take the angles from the point_viewcontrol.

**Comment by Balimbanana** [comment]
There is the kv for `angles`, but that is just for the initial angles and I don't think it takes in to account if it has changed by looking at a target or moving to a `path_track`. The initial angles might be enough to go on though.

**Comment by ZehMatt** [comment]
No I'm talking about changing the angles after the player has used SetViewEntity. Normally it should use the angles of the entity but for some reason it ignores it.

Edit: Ha a restart somehow managed to undo whatever was kaputt. Almost there.

**Comment by ZehMatt** [comment]
The latest develop branch should have both of them. Can you check if they are working correctly?

**Comment by Balimbanana** [comment]
It looks like the `point_viewcontrol` and `env_zoom` are working.

For `d2_coast_03` there is one last piece: `env_screenoverlay` which has to also be set for activator vs all players. I would probably default this one to be all players, and set specific instances when it should be for just the activator because it is used in quite a few maps throughout HL2, Ep1, and Ep2.

**Comment by ZehMatt** [comment]
Good catch, I haven't tested this with multiple people yet. I'll have a look at some point.

**Comment by ZehMatt** [comment]
Gotta close this as its implemented.
