### ISSUE TITLE
Scripted Sequence isn't executed properly because of missing target for the sequence

### ISSUE THREAD

**Issue by Sp-Lily** [ZehMatt/Lambda#126]
I think I know what's the cause of those citizen missing their pre-defined dialogue, also the game not run the scripted sequence properly. I got this kind of message generated on console:

`CSceneEntity lcs_sewercops_converse unable to find actor named "!target1"`
`CSceneEntity lcs_sewercops_converse unable to find actor named "!target2"`
`CSceneEntity lcs_sewercops_startle unable to find actor named "!target1"`
`CSceneEntity lcs_sewercops_startle unable to find actor named "!target2"`

This is the example where 2 Metro-Police doing conversation (sequence isn't executed) while I'm below them in map d1_canals_01a.

**Comment by ZehMatt** [comment]
This should be fixed on the develop branch.
