### ISSUE TITLE
Missing gesture happen on some maps causing NPC not playing specific animation

### ISSUE THREAD

**Issue by Sp-Lily** [ZehMatt/Lambda#127]
Here the list of the map and entity currently found, the list will be updated once more are found. Also their missing gestures are logged as error in the console:

- [x] **d1_canals_13:**
_Hidden singing Vort_

- [x] **d1_eli_01:**
_Vort Lab, Alyx_

- [ ] **d1_eli_02:**
Below are new and without conflicting addon installed
`CSceneEntity vort_Lab :"!target1" unable to find gesture "hg_acc_down"`
`CSceneEntity vort_fight_template :"!target1" unable to find gesture "hg_acc_down"`

**Comment by Sp-Lily** [comment]
Issue updated!

**Comment by knoxed** [comment]
Works fine, closing.
