### ISSUE TITLE
Replace killer trigger_hurt at d1_town_02

### ISSUE THREAD

**Issue by Sp-Lily** [ZehMatt/Lambda#130]
This trigger can be encountered after transfered from d1_town_03 to d1_town_02. Replace it with blocker or something instead of killing player with trigger_hurt.

**Trigger located here, exactly where I pointed my crosshair**
![hl2 2018-11-21 17-27-09-726](https://user-images.githubusercontent.com/16232605/48828421-faa6d800-edb2-11e8-9a1b-550ed1357ad3.png)

**Comment by Sp-Lily** [comment]
Btw, do you know about this? Have you try to play at this section?

**Comment by ZehMatt** [comment]
I think I placed it there so people wouldn't jump off as there is no way back for them, I'll have a look at some point.

**Comment by ZehMatt** [comment]
Actually you aren't supposed to reach this place, the door should be locked.

**Comment by ZehMatt** [comment]
This should be fixed, the door should no longer open.
