### ISSUE TITLE
Strange solid bright square @d2_coast_07 after switching off force field from d2_coast_08

### ISSUE THREAD

**Issue by Sp-Lily** [ZehMatt/Lambda#135]
![hl2 2018-11-21 22-46-02-376](https://user-images.githubusercontent.com/16232605/48911650-a1c06800-eeb6-11e8-82b2-0b0beed092f5.png)

**Comment by ZehMatt** [comment]
Haven't seen that before, thanks for reporting more issues.

**Comment by Sp-Lily** [comment]
No probs

**Comment by ZehMatt** [comment]
Turns out its a func_brush of the force field but I can not quite make out what the square is about. So I have to put this on hold for now.

**Comment by ZehMatt** [comment]
This seems to be no longer happening.
