### ISSUE TITLE
Convar to disable 'weapon autochange to best weapon'

### ISSUE THREAD

**Issue by FluffiestFloof** [ZehMatt/Lambda#174]
SelectBestWeapon becomes an issue when you are already quick switching weapons and the gamemode auto switch to something less useful in the current moment.

Exemple being when you run out of pistol ammo, switch to a crowbar then you get autoswitched to a SMG1 that hasn't been reloaded yet, or a grenade.

Not a huge issue, more like a quality of life thing.

**Comment by ZehMatt** [comment]
I noticed this before but never quite realized the bug, thanks for reporting.
