### ISSUE TITLE
No respawn setting

### ISSUE THREAD

**Issue by ZehMatt** [ZehMatt/Lambda#19]
If this option is enabled clients will be not able to respawn after death, they have to wait for the next map. Perhaps we can use the existing timeout value and use -1 for never respawn.

**Comment by knoxed** [comment]
Commit before that should be referenced too but forgot to include it in the commit message, now I'm having trouble updating the commit log message.

**Comment by ZehMatt** [comment]
You can use ammend, I'll close this.
