### ISSUE TITLE
A menu to configure specific addon features.

### ISSUE THREAD

**Issue by ghost** [ZehMatt/Lambda#198]
Is it possible to make a separate menu that has few spawnmenu features? I mean the ones that allow to config specific addon settings as an admin or user, like setting ArcCW crosshair, viewmodel, etc... and enabling Life Mod HUD while in gamemode.

Since we don't have spawnmenu yet, a feature like this would be cool.

**Comment by ZehMatt** [comment]
There will be no spawn menu ever, lambda is aimed to provide co-op to play with the campaign with other people and not a sandbox. If you want a spawn menu you can create an addon that adds it, there is no reason to have this in the core functionality. Also lambda can not provide a out of the box settings manager for every possible addon without having every addon to agree to some sort of common interface to interact with.
