### ISSUE TITLE
ArcCW Weapons do not work for NPCs.

### ISSUE THREAD

**Issue by Coleasice64** [ZehMatt/Lambda#199]
When playing this addon with myself or others, it can get bland having Combine carry around the same Half-Life 2 weapons. SO, I enable an option in ArcCW Base that allows HL2 NPCs to spawn with ArcCW weapons. However, they do absolutely zero damage and this is only a problem with Lambda. This is just a phenomenal Campaign addon and it sucks that this one issue is holding me back. Please look into this or at least tell me how I can fix it myself. Thanks!

**Comment by Coleasice64** [comment]
So, is this fix live or is it coming in another update?

**Comment by ZehMatt** [comment]
The fix is merged, the workshop entry has to be yet updated.
