### ISSUE TITLE
lambda_allow_npcdmg cvar not disabling NPC damage

### ISSUE THREAD

**Issue by PolarManne** [ZehMatt/Lambda#211]
Important NPCs always take damage from players regardless of whether `lambda_allow_npcdmg` is enabled or not. Taking out the `attackerIsPlayer == true` check fixes this (at the cost of making them completely invincible) so it seems to not be recognizing the source of damage correctly.

Additionally, temporarily essential NPCs like the one just before the manhacks on `d1_canals_03` are also not affected by the cvar at all. There's currently no check for this so consider this part to be a feature request.

**Comment by ZehMatt** [comment]
Thanks for the report, pretty sure it worked at some point. Some NPCs are also marked no longer important after finishing the objective, like in d1_canals_03 the NPC can be killed once the door opened without a mission fail. I will look into this.
