### ISSUE TITLE
MW2019 SWEPs Why is the gun invisible?

### ISSUE THREAD

**Issue by kilisys** [ZehMatt/Lambda#239]
I've made a gun but I can't see

**Comment by ZehMatt** [comment]
You need to provide more details about your issue if you want us to help you. If you made a gun using MW2019 SWEPs and its invisible you might want to check if the gun is also invisible when you use the gun in sandbox. If the gun is only invisible with Lambda I need a concrete way to reproduce the issue in order to solve it.

**Comment by kilisys** [comment]
I checked the sanbox, the gun works fine, but when it's in place, the Lambda doesn't see it.

**Comment by ZehMatt** [comment]
How would I go about testing this myself? Please provide the steps required to reproduce this.

**Comment by kilisys** [comment]
TFA Weapons ARC9 Weapons Compatible with Lambda

**Comment by kilisys** [comment]
_How would I go about testing this myself? Please provide the steps required to reproduce this._


thanks for listening

**Comment by ZehMatt** [comment]
I think some details are still missing, are you using the workshop addons or did you install them manually? Also which gun is invisible, all of them or just a specific one? You need to be a bit more concrete on how I would do this, which workshop addons or normal addons do I need to install and from where. Do I need to toggle any specific options or set specific convar values? The more information you provide the better

**Comment by kilisys** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2526457139
This add-on where i have all the problems

**Comment by kilisys** [comment]
I'm using the workshop add-on

**Comment by Aditorr** [comment]
I've had the same issue, for me every MWB weapon was invisible, functionality was just fine, and they didn't appear only in 
the Lambda gamemode, in sandbox they worked fine. As for replicating the issue, just spawning the weapons with sv_cheats 1 should give you an idea, In my case, I used an addon which replaced NPC weapons with weapons that of MWB. Also, the world models loaded, it seems to not load the weapon model in firstperson only.

**Comment by kilisys** [comment]
Would you update it or tell me how to fix it?

**Comment by Aditorr** [comment]
I've been wondering, have you attempted to recreate this issue? I've done it using an addon replacing default NPC weapons with MWB weapons (and of course all weapons from Modern Warfare Base). I've loaded into d1_canals_01 and killed the metrocops, after that any weapon they dropped I could normally pick up but the viewmodel would be invisible, functionality was fine tho.

**Comment by ZehMatt** [comment]
I've found the issue and will commit the fix asap.

**Comment by ZehMatt** [comment]
I've pushed a smaller release which should solve the issue with SWEPs.
