### ISSUE TITLE
Player not spawn at the right place after map change

### ISSUE THREAD

**Issue by dounai2333** [ZehMatt/Lambda#243]
After a player finished the map, if other players didn't reach the end before the timeout (lambda_map_change_timeout), he will spawn in the last map's position which is wrong.
I'm using the latest version from Steam Workshop.

How to reproduce:
1. Load d1_trainstation_02, and spawn a bot.
2. Teleport bot to -5330 -4480 5 ( lua_run Entity(2):SetPos(Vector(-5330, -4480, 5)) ).
3. Wait until the timeout occur and switch to next map.
4. You'll see you spawning in a void area (which the position is the spawn point of d1_trainstation_02)

**Comment by ZehMatt** [comment]
Thanks, I'll look into it.
