### ISSUE TITLE
Remove override models for next Garry's Mod update

### ISSUE THREAD

**Issue by ZehMatt** [ZehMatt/Lambda#298]
Garry's Mod provides them now out of the box, might need to keep some.

https://commits.facepunch.com/481021
https://commits.facepunch.com/482428

**Comment by knoxed** [comment]
The checked NPCs have their models combined by the game. NPCs written in bold are tricky to combine.

- [x] Alyx
- [x] **Advisor**
- [ ] Antlion
- [ ] Combine Dropship
- [ ] Dog
- [ ] Eli
- [ ] Fast zombie
- [x] Barney
- [x] Blackout (EP1 Intro)
- [x] Kleiner
- [ ] GMan
- [ ] **Lamarr**
- [x] Vortigaunt
- [ ] Mossman
- [ ] Zombie

**Comment by knoxed** [comment]
This can also be closed since Garry's Mod will provide all important models with their animations merged (upcoming October update).
