### ISSUE TITLE
Scripted Sequence Bug

### ISSUE THREAD

**Issue by ChapperNi** [ZehMatt/Lambda#336]
This happens on Street Hazard's campagin, the third map.

Found scripted_sequence with onplayerdeath set to 1: Entity [811][scripted_sequence] (standing_point1) at -9424.000000 -11696.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [812][scripted_sequence] (standing_point2) at -9712.000000 -11640.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [815][scripted_sequence] (standing_point_frohman) at -9808.000000 -11568.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [820][scripted_sequence] (standing_point_rebel2) at -9568.000000 -11344.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [821][scripted_sequence] (standing_point2_rebel2) at -9168.000000 -11204.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1059][scripted_sequence] (standing_point_frohman4) at -9788.000000 -10312.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1060][scripted_sequence] (standing_point_frohman2) at -9824.000000 -10496.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1061][scripted_sequence] (standing_point_frohman3) at -9808.000000 -11592.000000 -781.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1063][scripted_sequence] (standing_point_frohman5) at -9788.000000 -11324.000000 -781.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1095][scripted_sequence] (standing_point_frohman6) at -9792.000000 -10312.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1114][scripted_sequence] (standing_point2_rebel2_helper1) at -9408.000000 -11392.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1115][scripted_sequence] (standing_point2_rebel2_helper2) at -9192.000000 -11288.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1116][scripted_sequence] (rebel1_immediately_in_train) at -9808.000000 -11512.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1117][scripted_sequence] (rebel2_immediately_in_train) at -9828.000000 -11368.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1129][scripted_sequence] (rebel2_stand_still) at -9936.000000 -11392.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1130][scripted_sequence] (rebel1_stand_still) at -9936.000000 -11472.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
Found scripted_sequence with onplayerdeath set to 1: Entity [1131][scripted_sequence] (frohman_stand_still) at -9936.000000 -11432.000000 -783.000000 for map street_hazard_3
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues

**Comment by ZehMatt** [comment]
Thanks for the report, however you are playing maps that are unsupported and this message was meant to be shown only when we officially support that map, I will address the issue of displaying the message but its also a clear indication that without a map script the scripted sequence will be cancelled if a player dies.
