### ISSUE TITLE
Scripted Sequence Bug #2

### ISSUE THREAD

**Issue by ChapperNi** [ZehMatt/Lambda#337]
Encountered on the tr1p custom campaign, second map: https://steamcommunity.com/sharedfiles/filedetails/?id=2876372482

Found scripted_sequence with onplayerdeath set to 1: Entity [650][scripted_sequence] (constant_fastzombies_20s_spawn_roar1) at 1984.000000 2184.000000 560.000000 for map map2
If you see this message please submit a new issue on https://github.com/GMLambda/Lambda/issues
No map script was loaded for: map2

[Srlion's Hook Library] gamemodes/ezic/gamemode/sh_ents_extend.lua:111: Tried to use a NULL entity!
  1. GetInternalVariable - [C]:-1
   2. FindByGlobalName - gamemodes/ezic/gamemode/sh_ents_extend.lua:111
    3. func - gamemodes/ezic/gamemode/sv_transition.lua:776
     4. CreateTransitionObjects - gamemodes/ezic/gamemode/sv_transition.lua:59
      5. OnNewGame - gamemodes/ezic/gamemode/sh_roundsystem.lua:545
       6. func - gamemodes/ezic/gamemode/sh_roundsystem.lua:704
        7. ProcessQueue - gamemodes/ezic/gamemode/sh_utils.lua:510
         8. func - gamemodes/ezic/gamemode/sh_utils.lua:515
          9. internal_call - lua/includes/modules/hook.lua:409
           10. unknown - lua/includes/modules/hook.lua:428

**Comment by ZehMatt** [comment]
As explained in the other issue the warning about scripted_sequence is not supposed to show up for unsupported maps. As for the error I believe some addon is messing with ents.GetAll() which seems to contain invalid entities which is not supposed to happen as far I'm aware. Try removing all addons except Lambda.
