### ISSUE TITLE
d1_town_03 blocks level change if server starts directly on it

### ISSUE THREAD

**Issue by FluffyEevee** [ZehMatt/Lambda#73]
Not able to go towards the correct map as the changelevel is blocked by a red wall.
You can actually go back to d1_town_02 but it will lead to the player being stuck by a red wall and a trigger_hurt.

Observed on a dedicated server, without any other addons or modifications to the gamemode.

Probably not going to happen normally.

**Comment by ZehMatt** [comment]
Thanks for the report. That map can be quite tricky since it relies on the previous game state to progress to determine the path. This map is tricky because it goes back unlike other maps. I'll try to figure out a better way.
