### ISSUE TITLE
On d3_citadel_03, when you are supposed to get the Super Gravity Gun, it infinitly respawns it, crashing the game

### ISSUE THREAD

**Issue by 77Mynameislol77** [ZehMatt/Lambda#75]
It happens as soon as its converted from the normal gravity gun to the super gravity gun, before that happens, this code appears with the "lambda_log all" function

> [SV(16.815 45.300):Trigger] Entity [46][trigger_multiple]	Sending trigger update: 	false	0	
[SV(16.815 45.300):Trigger] Entity [46][trigger_multiple]	Sending trigger blocked: 	false	
[SV(16.815 45.301):Pickup] PlayerCanPickupWeapon	Player [1][Mynameislol]	Weapon [167][weapon_physcannon]	
[SV(16.815 45.301):Player] Respawning object Weapon [167][weapon_physcannon] in 1 seconds	
[SV(16.815 45.305):Pickup] PlayerCanPickupWeapon	Player [1][Mynameislol]	Weapon [167][weapon_physcannon]	
[SV(16.815 45.305):Player] Respawning object Weapon [167][weapon_physcannon] in 1 seconds	
[CL(16.815 45.306):Trigger] Trigger(46) new player count: 0	
[CL(16.815 45.306):Trigger] Received trigger block update	
[CL(16.815 45.306):Trigger] Trigger(46) now unblocked	
[SV(16.830 45.316):Pickup] PlayerCanPickupWeapon	Player [1][Mynameislol]	Weapon [167][weapon_physcannon]	
[SV(16.830 45.316):Player] Respawning object Weapon [167][weapon_physcannon] in 1 seconds	
[SV(16.830 45.316):Pickup] PlayerCanPickupWeapon	Player [1][Mynameislol]	Weapon [167][weapon_physcannon]	
[SV(16.830 45.316):Player] Respawning object Weapon [167][weapon_physcannon] in 1 seconds	
[SV(16.845 45.331):Pickup] PlayerCanPickupWeapon	Player [1][Mynameislol]	Weapon [167][weapon_physcannon]	
[SV(16.845 45.331):Player] Respawning object Weapon [167][weapon_physcannon] in 1 seconds	
[SV(16.845 45.331):Pickup] PlayerCanPickupWeapon	Player [1][Mynameislol]	Weapon [167][weapon_physcannon]	
[SV(16.845 45.331):Player] Respawning object Weapon [167][weapon_physcannon] in 1 seconds	
[SV(16.860 45.345):Pickup] PlayerCanPickupWeapon	Player [1][Mynameislol]	Weapon [167][weapon_physcannon]	
[SV(16.860 45.345):Player] Respawning object Weapon [167][weapon_physcannon] in 1 seconds	
[SV(16.860 45.345):Pickup] PlayerCanPickupWeapon	Player [1][Mynameislol]	Weapon [167][weapon_physcannon]	
[SV(16.860 45.345):Player] Respawning object Weapon [167][weapon_physcannon] in 1 seconds	
[SV(16.875 45.360):Pickup] PlayerCanPickupWeapon	Player [1][Mynameislol]	Weapon [167][weapon_physcannon]	
[SV(16.875 45.360):Player] Respawning object Weapon [167][weapon_physcannon] in 1 seconds	

I could avoid this by enabling sv_cheats, and noclipping away from the gravity gun as soon as it's dropped, and then come back after the conversion is completed, i'm pretty sure the game thinks the player can pick up the gravity gun, and tries to respawn it, but even though it can't, it respawns it anyway, and thus, looping

**Comment by ZehMatt** [comment]
Should be fixed in the development branch.
